# Experimental docker-compose for local use. Access `web` at localhost:30100.

version: "3.7"

volumes:
    local_data: {}

services:
    db:
        image: postgres:12.8-alpine@sha256:6f03854b0a6223f3b5efb98fe8a4d08af758d0625a6134dcae12c0a651f9e526
        volumes:
            - ./local_data:/var/lib/postgresql/
        ports:
            - "5432:5432"
        env_file:
            - .env.postgres.local
    redis:
        image: redis:6.2@sha256:143f7bfc2358911d6b36138eabfbfffea46273c5d4b5696d90e5cbf23d633cf8
    cron:
        build:
            context: .
            args:
                env: dev
        entrypoint: docker-php-entrypoint
        command: /var/www/html/run-cron.sh
        volumes:
            - .:/var/www/html
        env_file:
            - .env.local
        depends_on:
            - db
            - redis
    web:
        build:
            context: .
            args:
                env: dev
        ports:
            - "30100:80"
        volumes:
            - .:/var/www/html
        env_file:
            - .env.local
        depends_on:
            - db
            - redis
    adminer:
        image: adminer@sha256:e82c16620650d359b87284b598d9ae03e5d95f3412f45d1ef3936b803445f1ae
        ports:
            - "30101:8080"
